module.exports = {
  masterConfig: {
    create_people: "오더체크",
    template_name: "소유주",
    company_total: true,
    member_total: true,
    member_invite_total: true,
    auth_total: true,
    customer_total: true,
    calculate_total: true,
    file_total: true,
    form_total: true,
    chat_total: true,
    analytics_total: true,
    change_company_info: true,
    member_approval: true,
    member_del: true,
    member_detail_edit: true,
    member_invite: true,
    create_auth_template: true,
    edit_auth_template: true,
    del_auth_template: true,
    add_new_customer: true,
    customer_info_edit: true,
    integrate_customer: true,
    customer_del: true,
    calculate_upload_share: true,
    calculate_down: true,
    calculate_del: true,
    file_upload: true,
    file_down: true,
    file_del: true,
    create_form: true,
    edit_form: true,
    del_form: true,
    send_message: true,
    create_chat_room: true,
    del_chat_room: true,
    set_comment_template: true,
    set_chat: true,
    stat_access: true,
  },
  createConfig: {
    company_total: false,
    member_total: false,
    member_invite_total: false,
    auth_total: false,
    customer_total: false,
    calculate_total: false,
    file_total: false,
    form_total: false,
    chat_total: false,
    analytics_total: false,
    change_company_info: false,
    member_approval: false,
    member_del: false,
    member_detail_edit: false,
    member_invite: false,
    create_auth_template: false,
    edit_auth_template: false,
    del_auth_template: false,
    add_new_customer: false,
    customer_info_edit: false,
    integrate_customer: false,
    customer_del: false,
    calculate_upload_share: false,
    calculate_down: false,
    calculate_del: false,
    file_upload: false,
    file_down: false,
    file_del: false,
    create_form: false,
    edit_form: false,
    del_form: false,
    change_auth_open: false,
    change_whilte_label: false,
    send_message: false,
    create_chat_room: false,
    del_chat_room: false,
    set_comment_template: false,
    set_chat: false,
    stat_access: false,
  },
  limitPlan: {
    프리: {
      customer_count: 10,
      form_link_count: 3,
      fileStore: 0,
    },
    // 프리: {
    //   customer_count: 450,
    //   form_link_count: 410,
    // },
    스타터: {
      customer_count: 45,
      form_link_count: 40,
      fileStore: 5e11,
    },
    프로: {
      customer_count: 113,
      form_link_count: 100,
      fileStore: 1e12,
    },
    팀: {
      customer_count: 225,
      form_link_count: 205,
      fileStore: 1.5e12,
    },
    컴퍼니: {
      customer_count: 450,
      form_link_count: 410,
      fileStore: 2e12,
    },
  },
};
