module.exports = {
  masterConfig: {
    create_people: '오더체크',
    template_name: '소유주',
    company_total: true,
    member_total: true,
    member_invite_total: true,
    auth_total: true,
    customer_total: true,
    calculate_total: true,
    file_total: true,
    form_total: true,
    chat_total: true,
    analytics_total: true,
    change_company_info: true,
    member_approval: true,
    member_del: true,
    member_detail_edit: true,
    member_invite: true,
    create_auth_template: true,
    edit_auth_template: true,
    del_auth_template: true,
    add_new_customer: true,
    customer_info_edit: true,
    integrate_customer: true,
    customer_del: true,
    calculate_upload_share: true,
    calculate_down: true,
    calculate_del: true,
    file_upload: true,
    file_down: true,
    file_del: true,
    create_form: true,
    edit_form: true,
    del_form: true,
    change_auth_open: true,
    change_whilte_label: true,
    send_message: true,
    create_chat_room: true,
    del_chat_room: true,
    set_comment_template: true,
    set_chat: true,
    stat_access: true,
  },
  limitPlan: {
    FREE: {
      customer_count: 10,
      form_link_count: 3,
    },
    Starter: {
      customer_count: 45,
      form_link_count: 40,
    },
    PRO: {
      customer_count: 113,
      form_link_count: 100,
    },
    TEAM: {
      customer_count: 225,
      form_link_count: 205,
    },
    COMPANY: {
      customer_count: 450,
      form_link_count: 410,
    },
  },
};
